#!/usr/bin/env -S ANSIBLE_STDOUT_CALLBACK=yaml ansible-playbook -i localhost,
---
- hosts: localhost
  connection: local
  force_handlers: true
  vars:
    ansible_python_interpreter: auto_silent

  pre_tasks:
    - set_fact:
        eff_uid_number: "{{ lookup('pipe', 'id -u') }}"

    - block:
      - debug:
          msg: "This program requires root privileges"
      - meta: end_play
      when: eff_uid_number|int != 0

  roles:
    - docker
