---
- name: System-specific installation of docker-ce
  include_tasks: "setup-{{ansible_distribution |replace(' ', '_')}}.yml"

- name: Upload daemon.json
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
  notify:
    - restart docker

- name: Add user to docker group
  user:
    name: '{{docker_user}}'
    groups: docker
    append: yes
  when: docker_user is defined


- name: Install additional tools
  include_tasks: tools.yml
  

- meta: flush_handlers
