---
- set_fact:
    distname: "{{ ansible_distribution| lower| replace(' ', '_') }}"

- debug: msg="Using '{{distname}}' as internal distribution name."

- name: System-specific installation of docker-ce
  include_tasks: "setup-{{distname}}.yml"

- name: Start and enable docker service
  service:
    name: docker
    state: started
    enabled: yes

- name: Upload daemon.json
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
  notify:
    - restart docker

- meta: flush_handlers


- name: Add user to docker group
  user:
    name: '{{docker_user}}'
    groups: docker
    append: yes
  when: docker_user is defined


- name: Install bash-completion package
  package:
    name: bash-completion


- include_tasks: "lazydocker.yml"


- debug: msg="No Python SDK modules were installed."
