---
- name: System-specific installation of docker-ce
  include_tasks: "setup-{{ansible_distribution |replace(' ', '_')}}.yml"

- name: Start and enable docker service
  service:
    name: docker
    state: started
    enabled: yes

- name: Upload daemon.json
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
  notify:
    - restart docker

- meta: flush_handlers


- name: Add user to docker group
  user:
    name: '{{docker_user}}'
    groups: docker
    append: yes
  when: docker_user is defined


- name: Install bash-completion package
  package:
    name: bash-completion

- name: Install additional tools
  include_tasks: tools.yml


- block:
    - name: Make installation via pip possible on Debian 12
      file:
        path: /usr/lib/python3.11/EXTERNALLY-MANAGED
        state: absent
      when: ansible_distribution == "Debian"
              and
            ansible_distribution_major_version is_version('12', '==')

    - name: Install requirements for pip usage
      package:
        name:
          - python3-pip
          - python3-setuptools

    - name: Install required Python modules
      pip:
        name:
          - docker
          - docker-compose
  when: docker_sdk | bool

  # TODO: We should prefer distribution packages, at least if possible!