---
- name: Update apt cache
  apt: 
    update_cache: yes
    cache_valid_time: 3600

- name: Install some prereqs
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - gnupg

- name: Import Dockers official GPG key
  get_url:
    url: https://download.docker.com/linux/{{ansible_distribution|lower}}/gpg
    dest: /etc/apt/keyrings/docker-archive-keyring.asc
    
- name: Add docker apt repo
  apt_repository:
    repo: >-
      deb [signed-by=/etc/apt/keyrings/docker-archive-keyring.asc]
      https://download.docker.com/linux/{{ansible_distribution|lower}}
      {{ansible_lsb.codename}} stable
    filename: docker-ce
    state: present

- name: Install docker-ce
  apt:
    name: docker-ce
